const companies = [
  { name: "Accenture", logo: "/Accenture.webp", color: "#2C2C2C" },
  { name: "TCS", logo: "/TCS.webp", color: "#F0A000" },
  { name: "Infosys", logo: "/Infosys.webp", color: "#009C8C" },
  { name: "Wipro", logo: "/Wipro.webp", color: "#5F5A5A" },
  { name: "Zoho", logo: "/Zoho.webp", color: "#0076D6" },
  { name: "Salesforce", logo: "/Salesforce.webp", color: "#00A1E0" },
  { name: "IBM", logo: "/IBM.webp", color: "#006699" },
  { name: "HCL", logo: "/HCL.webp", color: "#0064A3" },
  { name: "Tech Mahindra", logo: "/TechMahindra.webp", color: "#A9A9A9" },
  { name: "SwiftNLift", logo: "/SwiftNLift.webp", color: "#1D6F82" },
  { name: "PrimeTycoon", logo: "/Prime.webp", color: "#1D6F82" },
  { name: "ArrayLogic", logo: "/ArrayLogo.webp", color: "#1D6F82" },
  {
    name: "Exacore IT Solutions",
    logo: "/ExacoreITSolutions.webp",
    color: "#8B0000",
  },
  {
    name: "Globant India Pvt. Ltd",
    logo: "/GlobantIndia.webp",
    color: "#1D6F82",
  },
  {
    name: "Greentin Solutions",
    logo: "/GreentinSolutions.webp",
    color: "#32CD32",
  },
  {
    name: "Sasken Technologies ",
    logo: "/SaskenTechnologies.webp",
    color: "#FF4500",
  },
  {
    name: "DevLogic Technologies",
    logo: "/DevLogicTechnologies.webp",
    color: "#000080",
  },
  {
    name: "YASH Technologies",
    logo: "/YASHTechnologies.webp",
    color: "#FFD700",
  },
  { name: "Mindtree Ltd", logo: "/Mindtree.webp", color: "#9400D3" },
  {
    name: "Leometric Technology",
    logo: "/LeometricTechnology.webp",
    color: "#DC143C",
  },
  {
    name: "Allygrow Technologies",
    logo: "/AllygrowTechnologies.webp",
    color: "#006400",
  },
  { name: "e-Zest Solutions", logo: "/EZestSolutions.webp", color: "#8A2BE2" },
  { name: "iASYS Technology ", logo: "/IASYSTechnology.webp", color: "#FF6347" },
  { name: "NXG Labs Pvt Ltd", logo: "/NXGLabs.webp", color: "#8B008B" },
  {
    name: "Lonar Technologies ",
    logo: "/LonarTechnologies.webp",
    color: "#9932CC",
  },
  { name: "Vyom Labs ", logo: "/VyomLabs.webp", color: "#2E8B57" },
  { name: "CoreView Systems ", logo: "/CoreViewSystems.webp", color: "#8B0000" },
  { name: "PubMatic India ", logo: "/PubMaticIndia.webp", color: "#B22222" },
  { name: "Enzigma Software ", logo: "/EnzigmaSoftware.webp", color: "#D2691E" },
  {
    name: "Sarvatra Technologies",
    logo: "/SarvatraTechnologies.webp",
    color: "#000080",
  },
  {
    name: "Thinkitive Technologies ",
    logo: "/ThinkitiveTechnologies.webp",
    color: "#FFD700",
  },
  {
    name: "Allied Softech Pvt. Ltd",
    logo: "/AlliedSoftech.webp",
    color: "#2F4F4F",
  },
  { name: "Nabla Infotech ", logo: "/NablaInfotech.webp", color: "#008080" },
  { name: "Bentley Systems", logo: "/BentleySystems.webp", color: "#008B8B" },
  { name: "Xento Systems", logo: "/XentoSystems.webp", color: "#ADFF2F" },
  { name: "Avaya India Pvt. Ltd", logo: "/AvayaIndia.webp", color: "#DC143C" },
  { name: "AGS Technologies", logo: "/AGSTechnologies.webp", color: "#00008B" },
  {
    name: "Capsilon Software",
    logo: "/CapsilonSoftware.webp",
    color: "#9ACD32",
  },
  {
    name: "Nesecure Networks ",
    logo: "/NesecureNetworks.webp",
    color: "#DAA520",
  },
  {
    name: "SoftwareGen Technologies",
    logo: "/SoftwareGenTechnologies.webp",
    color: "#8B008B",
  },
  {
    name: "Edzeal Technologies",
    logo: "/EdzealTechnologies.webp",
    color: "#FF4500",
  },
  {
    name: "Bytzsoft Technologies",
    logo: "/BytzsoftTechnologies.webp",
    color: "#8A2BE2",
  },
];

export default companies;
